### ISSUE TITLE
'log_level' is not valid in section 'ercf'

### ISSUE THREAD

**Issue by RcTomcat1** [EtteGit/EnragedRabbitProject#182]
Hi,
just updated klipper and I am running into quite a lot of issues with my ercf setup.
Basically every config line is "not valid" anymore. 
Log_level, log_statistics, servo_up_angle, servo_down_angle and so on.

What I tried so far:
I recreated the ercf.py, that did not solve anything.

System:
Klipper v0.11.0-89-gead81fbf 

Last lines of theLog:
`Config error
Traceback (most recent call last):
  File "/home/pi/klipper/klippy/klippy.py", line 175, in _connect
    self._read_config()
  File "/home/pi/klipper/klippy/klippy.py", line 145, in _read_config
    pconfig.check_unused_options(config)
  File "/home/pi/klipper/klippy/configfile.py", line 301, in check_unused_options
    % (option, section))
Error: Option 'log_level' is not valid in section 'ercf'
webhooks client 547576676432: New connection
webhooks client 547576676432: Client info {'program': 'Moonraker', 'version': 'v0.7.1-826-g1bad68c'}`

What else might I check to get this working again?

**Comment by TheBiz73** [comment]
I too am having this issue. Did you find a solution?
